# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ted Talk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'lottie-ios'
  pod 'RealmSwift'

  target 'Ted TalkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Ted TalkUITests' do
    # Pods for testing
  end

end
